# UI Texts: Main Menu - top-level menus specific to this application.
MainMenu_Equates.label=&Equates
MainMenu_View.label=&View

# UI Texts: Main Menu - File.
MainMenu_File_NewWorkspace.label=&New Workspace
MainMenu_File_OpenWorkspace.label=&Open Workspace...
MainMenu_File_OpenFile.label=Open &File
MainMenu_File_OpenCassetteImageFile.label=Open &Cassette Image File...
MainMenu_File_OpenDiskImageExecutableFile.label=Open &Disk Image Executable File...
MainMenu_File_OpenDiskImageBootSectors.label=Open Disk Image &Boot Sectors...
MainMenu_File_OpenDiskImageSectors.label=Open Disk Image &Sectors...
MainMenu_File_OpenExecutableFile.label=Open E&xecutable File...
MainMenu_File_OpenRawFile.label=Open Raw &File...
MainMenu_File_OpenROMImageFile.label=Open &ROM Image File...
MainMenu_File_AddFile.label=Add F&ile
MainMenu_File_AddCassetteImageFile.label=Add &Cassette Image File...
MainMenu_File_AddDiskImageExecutableFile.label=Add &Disk Image Executable File...
MainMenu_File_AddDiskImageBootSectors.label=Add Disk Image &Boot Sectors...
MainMenu_File_AddDiskImageSectors.label=Add Disk Image &Sectors...
MainMenu_File_AddExecutableFile.label=Add E&xecutable File...
MainMenu_File_AddRawFile.label=Add Raw &File...
MainMenu_File_AddROMImageFile.label=Add &ROM Image File...
MainMenu_File_SaveWorkspace.label=&Save Workspace
MainMenu_File_SaveWorkspaceAs.label=Save Workspace &As...
MainMenu_File_SaveDisassemblyFiles.label=Save &Disassembly Files...
MainMenu_File_WriteBootDisk.label=&Write Boot Disk...
MainMenu_File_RecentWorkspaces.label=&Recent Workspaces
MainMenu_File_RecentFiles.label=R&ecent Files
MainMenu_File_Exit.label=E&xit

# UI Texts: Main Menu - Equates.
MainMenu_Equates_ClearSystemEquates.label=Clear S&ystem Equates
MainMenu_Equates_DisplaySystemEquates.label=Display &System Equates
MainMenu_Equates_ClearUserEquates.label=C&lear User Equates
MainMenu_Equates_EditUserEquates.label=&Edit User Equates...
MainMenu_Equates_DefineUserAddressRange.label=Define &Address Range...
MainMenu_Equates_OpenUserEquates.label=&Open User Equates...
MainMenu_Equates_SaveUserEquates.label=&Save User Equates...
MainMenu_Equates_ExportUserEquates.label=E&xport User Equates...

# UI Texts: Main Menu - View.
MainMenu_View_DisplayAsScreenCode.label=Display as &Screen Code
MainMenu_View_NoDisassembly.label=&No Disassembly
MainMenu_View_DoubleFontHeight.label=&Double Font Height
MainMenu_View_DefaultFolders.label=Default &Folders...
MainMenu_View_Profile.label=&Profile...

# UI Texts: Main Menu - Help.
MainMenu_Help_About.label=&About...
