# General.
Profile_CommentPrefix.label=&Comment:
Profile_HexNotationPrefix.label=&Hex Prefix:
Profile_UseIllegalOpcodes.label=&Illegal Instructions
Profile_UseHexNotation.label=&Use Hex Notation
Profile_AlignInstructions.label=&Align Instructions
Profile_UseLineNumbers.label=Use &Line Numbers
Profile_ShowLowerCaseInstructions.label=&Show Lowercase Instructions
Profile_ShowAInAccumulatorMode.label=Show 'A' in Accumulat&or Mode
Profile_ShowColonAfterLabel.label=Show ':' a&fter Labels
Profile_ShowOpcodeAsComment.label=Show O&pcode as Comment
Profile_ShowBRKAsByte0.label=Show '&BRK' as '.BYTE $00'
Profile_ShowZPAbsoluteAsByte.label=Show &ZP Addr. in Absolute Mode as Bytes
Profile_DirectiveForceAbsolute.label=&Mnemonic to force Absolute Mode:
Profile_ShowNonASCIIChararactersAsBytes.label=Show &Non-ASCII Characters as Bytes
Profile_DirectiveBYTENumberOfBytesPerLine.label=Number of Byte &Values per Line:
Profile_DirectiveWORDNumberOfWordsPerLine.label=Number of &Word Values per Line:
Profile_DirectiveBYTENumberOfCharactersPerString.label=Number of Charac&ters per String:
Profile_QuoteForASCIIStrings.label=&Quote for ASCII Strings:
Profile_QuoteForASCIIStrings.toolTip=Only the first character of this string is used

# Directive Syntax.
Profile_DirectiveBYTE.label=.&BYTE:
Profile_DirectiveBYTESeparator.label=&Separator:
Profile_DirectiveBYTEOnlyNumbersAllowed.label=&Only Numbers in .BYTE
Profile_DirectiveWORDAllowed.label=.&WORD Allowed:
Profile_DirectiveSBYTEAllowed.label=.SB&YTE Allowed:
Profile_DirectiveORG.label=.O&RG:
Profile_DirectiveLOWHead.label=&Low Byte (ADDR):
Profile_DirectiveEQU.label=&EQU:
Profile_DirectiveHIGHHead.label=&High Byte (ADDR):
Profile_DirectiveENDHead.label=.E&ND:
Profile_DirectiveENDNeedsFilename.label=&Add File Name
Profile_DirectiveDSAllowed.label=.&DS (Data Storage) Allowed:

# Disassembly Listing.
Profile_OutputEncoding.label=&Encoding:
Profile_OmitUnreferencedSystemLabels.label=&Omit Unreferenced System Labels
Profile_DirectiveINCLUDEAllowed.label=&Include Files Allowed
Profile_DirectiveINCLUDEHead.label=.I&NCLUDE:
Profile_DirectiveINCLUDETail.label=&FILENAME:
Profile_DirectiveINCLUDEAllEquatesInOneIncludeFile.label=One File for E&quates included in Main File
Profile_DirectiveINCLUDEAllIncludesInMainFile.label=&All Files Included in Main File
Profile_DirectiveINCLUDEEachFileIncludesNextFile.label=Each File Includes Ne&xt File
Profile_DirectiveINCLUDEMaximumNumberOfLinesPerFile.label=&Maximum Number of Lines per Include File:
