# General.
Profile_CommentPrefix.label=&Comment:
Profile_HexNotationPrefix.label=&Hex Prefix:
Profile_UseIllegalOpcodes.label=&Illegal Instructions
Profile_UseHexNotation.label=&Use Hex Notation
Profile_AlignInstructions.label=&Align Instructions
Profile_UseLineNumbers.label=Use &Line Numbers
Profile_ShowLowerCaseInstructions.label=&Show Lowercase Instructions
Profile_ShowAInAccumulatorMode.label=Show 'A' in Accumulat&or Mode
Profile_ShowColonAfterLabel.label=Show ':' a&fter Labels
Profile_ShowOpcodeAsComment.label=Show O&pcode as Comment
Profile_ShowBRKAsByte0.label=Show '&BRK' as '.BYTE $00'
Profile_ShowZPAbsoluteAsByte.label=Show &ZP Addr. in Absolute Mode as Bytes
Profile_DirectiveForceAbsolute.label=&Mnemonic to force Absolute Mode:
Profile_ShowNonASCIIChararactersAsBytes.label=Show &Non-ASCII Characters as Bytes
Profile_DirectiveBYTENumberOfBytesPerLine.label=Number of Byte &Values per Line:
Profile_DirectiveWORDNumberOfWordsPerLine.label=Number of &Word Values per Line:
Profile_DirectiveBYTENumberOfCharactersPerString.label=Number of Charac&ters per String:
Profile_QuoteForASCIIStrings.label=&Quote for ASCII Strings:
Profile_QuoteForASCIIStrings.toolTip=Only the first character of this string is used

# Directive Syntax.
Profile_DirectiveBYTE.label=.&BYTE:
Profile_DirectiveBYTESeparator.label=&Separator:
Profile_DirectiveBYTEOnlyNumbersAllowed.label=&Only Numbers in .BYTE
Profile_DirectiveWORDAllowed.label=.&WORD Allowed:
Profile_DirectiveSBYTEAllowed.label=.SB&YTE Allowed:
Profile_DirectiveORG.label=.O&RG:
Profile_DirectiveLOWHead.label=&Low Byte (ADDR):
Profile_DirectiveEQU.label=&EQU:
Profile_DirectiveHIGHHead.label=&High Byte (ADDR):
Profile_DirectiveENDHead.label=.E&ND:
Profile_DirectiveENDNeedsFilename.label=&Add File Name
Profile_DirectiveDSAllowed.label=.&DS (Data Storage) Allowed:

# Disassembly Listing.
Profile_OutputEncoding.label=&Encoding:
Profile_OmitUnreferencedSystemLabels.label=&Omit Unreferenced System Labels
Profile_DirectiveINCLUDEAllowed.label=&Include Files Allowed
Profile_DirectiveINCLUDEHead.label=.I&NCLUDE:
Profile_DirectiveINCLUDETail.label=&FILENAME:
Profile_DirectiveINCLUDEAllEquatesInOneIncludeFile.label=One File for E&quates included in Main File
Profile_DirectiveINCLUDEAllIncludesInMainFile.label=&All Files Included in Main File
Profile_DirectiveINCLUDEEachFileIncludesNextFile.label=Each File Includes Ne&xt File
Profile_DirectiveINCLUDEMaximumNumberOfLinesPerFile.label=&Maximum Number of Lines per Include File:

# AssembleDialog.
AssembleDialog_Address.label=&New Instruction at:
AssembleDialog_Result.label=&Result:

# DisassemblyProgressDialog.
DisassemblyProgressDialog_Pass.label=&Pass:
DisassemblyProgressDialog_Segment.label=&Segment:

# DiskImageExecutableFileDialog.
DiskImageExecutableFileDialog_DiskImageFile.label=&Disk Image File:
DiskImageExecutableFileDialog_ExecutableFileName.label=&Executable File Name:

# DiskImageSectorsDialog.
DiskImageSectorsDialog_DiskImageFile.label=&Disk Image File:
DiskImageSectorsDialog_Address.label=&Address ($):

# EquateDialog.
EquateDialog_Equate.label=&Equate

# EquateRangeDialog.
EquateRangeDialog_StartAddress.label=&Start Address ($):
EquateRangeDialog_EndAddress.label=&End Address ($):
EquateRangeDialog_RelativeToEquate.label=&Relative to Equate:

# LowHighByteDialog.
LowHighByteDialog_LowByte.label=&Low Byte ($):
LowHighByteDialog_HighByte.label=&High Byte ($):

# MemoryInspectorFindStringDialog.
MemoryInspectorFindStringDialog_AsciiString.label=&String:
MemoryInspectorFindStringDialog_Hex.label=&Hex:
MemoryInspectorFindStringDialog_AllSegments.label=&All Segments
MemoryInspectorFindStringDialog_SelectedSegment.label=Se&lected Segment

# RawFileDialog.
RawFileDialog_FilePath.label=&File:
RawFileDialog_StartOffset.label=&Start Offset:
RawFileDialog_EndOffset.label=&End Offset:
RawFileDialog_Address.label=&Address ($):

# SegmentPropertiesDialog.
SegmentPropertiesDialog_Address.label=&Address ($):
SegmentPropertiesDialog_LabelPrefix.label=&Label Prefix:
SegmentPropertiesDialog_Processor.label=&Processor:
SegmentPropertiesDialog_Binary.label=&Binary

# SegmentWriteBootDiskDialog.
SegmentWriteBootDiskDialog_LoadAddress.label=&Load Address: $
SegmentWriteBootDiskDialog_InitAddress.label=&Init Address: $

# SelectGraphicsDialog.
SelectGraphicsDialog_GraphicMode.label=&Graphic Mode:
SelectGraphicsDialog_BytesPerLine.label=&Bytes per Line:
SelectGraphicsDialog_Address.label=&Address:

# TextFontDialog.
TextFontDialog_Font.label=&Font:

# WorkspaceDialog.
WorkspaceDialog_ComputerSystem.label=&Computer System:
